### ISSUE TITLE
..../lib/ubuntu/libFaceAPI.so: undefined symbol: CropFace

### ISSUE THREAD

**Issue by huxianhe0** [tensorflower/seetaFace6Python#1]
![avatar](https://raw.githubusercontent.com/huxianhe0/Pictures/master/2020-05-09%2011-19-33.png)

self._CropFace = dll.CropFace
这里报错：
/lib/ubuntu/libFaceAPI.so: undefined symbol: CropFace

![avatar](https://raw.githubusercontent.com/huxianhe0/Pictures/master/2020-05-09%2011-30-59.png)
此外还有open the model file failed的错误

求楼主指点

**Comment by tensorflower** [comment]
> ![avatar](https://raw.githubusercontent.com/huxianhe0/Pictures/master/2020-05-09%2011-19-33.png)
> 
> self._CropFace = dll.CropFace
> 这里报错：
> /lib/ubuntu/libFaceAPI.so: undefined symbol: CropFace
> 
> 求楼主指点

代码已更新，重新下载即可

**Comment by huxianhe0** [comment]
> > ![avatar](https://raw.githubusercontent.com/huxianhe0/Pictures/master/2020-05-09%2011-19-33.png)
> > self._CropFace = dll.CropFace
> > 这里报错：
> > /lib/ubuntu/libFaceAPI.so: undefined symbol: CropFace
> > 求楼主指点
> 
> 代码已更新，重新下载即可

感谢，回复的很快！
但还是有读取model不成功的问题，求指点

![avatar](https://raw.githubusercontent.com/huxianhe0/Pictures/master/2020-05-09-11.png)

**Comment by huxianhe0** [comment]
ERROR: open the model file:seetaface/model/face_detector.csta failed!
读到的都是相对路径，请问改写哪里，可以让open model读到绝对路径，例如这种的：
/home/zhaogang/Cpp/seetaFace6Python/seetaface/model/face_detector.csta

**Comment by tensorflower** [comment]
> ERROR: open the model file:seetaface/model/face_detector.csta failed!
> 读到的都是相对路径，请问改写哪里，可以让open model读到绝对路径，例如这种的：
> /home/zhaogang/Cpp/seetaFace6Python/seetaface/model/face_detector.csta

没有添加这个设置，请在与seetaface 目录同级下执行python文件
