### ISSUE TITLE
请教大佬，如何打印抽取出来的特征向量呢？

### ISSUE THREAD

**Issue by yangbisheng2009** [tensorflower/seetaFace6Python#10]
face_recon_demo.py 文件中

 21 #提取第一张图中的人脸特征
 22 image = cv2.imread("asserts/1.jpg")
 23 detect_result1 = seetaFace.Detect(image)
 24 face1 = detect_result1.data[0].pos
 25 points1 = seetaFace.mark5(image, face1)
 26 feature1 = seetaFace.Extract(image, points1)
 **27 print(feature1)**

这种打印方式只能打出来内存地址，无法把向量内容打印出来

**Comment by tensorflower** [comment]
> face_recon_demo.py 文件中
> 
> 21 #提取第一张图中的人脸特征
> 22 image = cv2.imread("asserts/1.jpg")
> 23 detect_result1 = seetaFace.Detect(image)
> 24 face1 = detect_result1.data[0].pos
> 25 points1 = seetaFace.mark5(image, face1)
> 26 feature1 = seetaFace.Extract(image, points1)
> **27 print(feature1)**
> 
> 这种打印方式只能打出来内存地址，无法把向量内容打印出来

特征值本来就是内存地址，无法直接看的。要看需要对特征对象调用get_feature_numpy ,或者get_feature_base64，可以看到
