### ISSUE TITLE
判断系统类型的方法不可靠

### ISSUE THREAD

**Issue by SuperChrisliu** [tensorflower/seetaFace6Python#14]
我的centos platform.platform().lower()返回的信息：  linux-3.10.0-1062.el7.x86_64-x86_64-with-glibc2.17

**Comment by tensorflower** [comment]
> 我的centos platform.platform().lower()返回的信息： linux-3.10.0-1062.el7.x86_64-x86_64-with-glibc2.17

是centos7系统吗？如果是，出现这样的情况，需要自己修改判断平台那行代码
