### ISSUE TITLE
[ERROR]: [src/runtime/instruction.cpp:65]

### ISSUE THREAD

**Issue by AIwzx** [tensorflower/seetaFace6Python#16]
Check failed: (stack.size() >= static_cast<size_t>(return_size)).
terminate called after throwing an instance of 'ts::api::Exception'
  what():  [src/runtime/instruction.cpp:65]: Check failed: (stack.size() >= static_cast<size_t>(return_size)).

**Comment by tensorflower** [comment]
> Check failed: (stack.size() >= static_cast<size_t>(return_size)).
> terminate called after throwing an instance of 'ts::api::Exception'
> what(): [src/runtime/instruction.cpp:65]: Check failed: (stack.size() >= static_cast<size_t>(return_size)).

这是做哪行调用时报的错？

**Comment by AIwzx** [comment]
特征比对的时候调用出错，不知道啥情况

**Comment by tensorflower** [comment]
> 特征比对的时候调用出错，不知道啥情况

应该是调用函数时，放入两个特诊值对象有问题，需要放出具体代码

**Comment by AIwzx** [comment]
我用的你的人脸比对代码做的接口，里面用了try了，c++我也不太懂啊 只知道出现这个error就退出了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"GitHub"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 上午10:15
收件人:&nbsp;"tensorflower/seetaFace6Python"<seetaFace6Python@noreply.github.com&gt;;
抄送:&nbsp;"兴"<1035459700@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflower/seetaFace6Python] [ERROR]: [src/runtime/instruction.cpp:65] (#16)





  
特征比对的时候调用出错，不知道啥情况
  
应该是调用函数时，放入两个特诊值对象有问题，需要放出具体代码

**Comment by tensorflower** [comment]
> 我用的你的人脸比对代码做的接口，里面用了try了，c++我也不太懂啊 只知道出现这个error就退出了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"GitHub"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月2日(星期四) 上午10:15 收件人:&nbsp;"tensorflower/seetaFace6Python"<seetaFace6Python@noreply.github.com&gt;; 抄送:&nbsp;"兴"<1035459700@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [tensorflower/seetaFace6Python] [ERROR]: [src/runtime/instruction.cpp:65] (#16) 特征比对的时候调用出错，不知道啥情况 应该是调用函数时，放入两个特诊值对象有问题，需要放出具体代码 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个报错，看不出来具体原因，我觉得很可能是在你的项目李这个特诊没有提取到，传了空特征，你测试下代码提供的人脸对比demo文件，那个能正常得到测试对比结果就没有问题
