### ISSUE TITLE
如何生成.so文件的？

### ISSUE THREAD

**Issue by bleakie** [tensorflower/seetaFace6Python#17]
请教作者，如何在ubuntu下生成.so文件？每次调用seetaface的模块就会出现这个错误 what():  std::bad_alloc
代码如下：
`
extern "C"
{void test(int height, int width, int channel, uchar* frame_data)
{
    std::cout << "kaishi c++" << std::endl;
    cv::Mat image(height, width, CV_8UC3);
    memcpy(image.data, frame_data, sizeof(uchar) * width * height * channel);
    seeta::FaceDetector FD(seeta::ModelSetting(ModelPath + "face_detector.csta"));
    seeta::FaceLandmarker PD(seeta::ModelSetting(ModelPath + "face_landmarker_pts5.csta"));
    return;
}}
`

**Comment by tensorflower** [comment]
> 请教作者，如何在ubuntu下生成.so文件？每次调用seetaface的模块就会出现这个错误 what(): std::bad_alloc
> 代码如下：
> `extern "C" {void test(int height, int width, int channel, uchar* frame_data) { std::cout << "kaishi c++" << std::endl; cv::Mat image(height, width, CV_8UC3); memcpy(image.data, frame_data, sizeof(uchar) * width * height * channel); seeta::FaceDetector FD(seeta::ModelSetting(ModelPath + "face_detector.csta")); seeta::FaceLandmarker PD(seeta::ModelSetting(ModelPath + "face_landmarker_pts5.csta")); return; }}`

这个是我提供的代码产生的错误日志吗？看起来好像不太像呢

**Comment by bleakie** [comment]
不是你的日志，是我的错误，现在已经转成功了
期待早日出quality dll
