### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by gaojingloudev** [tensorflower/seetaFace6Python#23]
作者，你好我这边用你的代码，出现了疑似内存泄漏的问题。分为两种情况:
声明一下，我是用你的代码做N对N的人脸识别(遍历1对N)
1.人脸检测部分使用的是mtcnn，因为发现你封装的人脸检测没有mtcnn的准。在多次debug之后，再debug会出现"Memory error ......"的错误，我的浏览器也会因为运行该程序而崩溃，但是重启计算机后就可以重新debug了，debug一段时间后又会出现该问题。
2.人脸的检测与识别都是用你的代码，遍历人脸库的证件照片与检测到的人脸进行形似度比对，会出现"libpng warning: iCCP: known incorrect sRGB profile"还没跑完然后断掉。

**Comment by tensorflower** [comment]
> debug

第一个问题：建议你直接用demo代码 while True 执行，不要涉及个人业务代码，就单独的跑下自己的一些人脸检测图片，看看是否会这样。 第二个问题：应该是你的截图，png图片，但是你命名成了.jpg，这个时warn，不是报错，应该没事
