### ISSUE TITLE
ERROR: open the model file:seetaface/model/face_detector.csta failed!

### ISSUE THREAD

**Issue by dingjianfei** [tensorflower/seetaFace6Python#3]
ERROR: open the model file:seetaface/model/face_detector.csta failed!
ERROR: open the model file:seetaface/model/face_landmarker_pts5.csta failed!
FL5Init errorERROR: open the model file:seetaface/model/age_predictor.csta failed!
<seetaface.api.SeetaFace object at 0x7f8b3babecf8>

**Comment by zhys513** [comment]
百度网盘：https://pan.baidu.com/share/init?surl=LlXe2-YsUxQMe-MLzhQ2Aw 提取码：ngne
将下载的所有 *.csta 模型文件 放入 seetaFace6Python/seetaface/model 目录下
