### ISSUE TITLE
导入seetaface.api 非法指令

### ISSUE THREAD

**Issue by jiehui87** [tensorflower/seetaFace6Python#31]
from seetaface.api import *
非法指令

请问有人知道怎么解决么

**Comment by tensorflower** [comment]
查看机器以下几个指令集 是否都支持AVX | SSE | FMA

**Comment by tensorflower** [comment]
查看机器以下几个指令集 是否都支持AVX | SSE | FMA

> from seetaface.api import *
> 非法指令
> 
> 请问有人知道怎么解决么

查看机器以下几个指令集 是否都支持AVX | SSE | FMA
