### ISSUE TITLE
get_feature_numpy 接口返回值错误，建议使用dtype=np.float32，当前返回int32 ，不适于计算feature 距离

### ISSUE THREAD

**Issue by fantasylzp** [tensorflower/seetaFace6Python#35]
file ： api.py        

line 423:  face_encoding = (
            np.frombuffer(string_at(feature, 1024 * 4), dtype=np.float32))

建议修改如上

**Comment by tensorflower** [comment]
> file ： api.py
> 
> line 423: face_encoding = (
> np.frombuffer(string_at(feature, 1024 * 4), dtype=np.float32))
> 
> 建议修改如上

对的，是我的疏忽，感谢，已经修改
