### ISSUE TITLE
几个并发请求就会报错，杀掉整个程序

### ISSUE THREAD

**Issue by w-Bro** [tensorflower/seetaFace6Python#43]
使用fastapi部署成http接口，jmeter2个线程请求正常，5个线程就报错，整个程序被杀死
```
[ERROR]: [src/runtime/instruction.cpp:65]: Check failed: (stack.size() >= static_cast<size_t>(return_size)).
terminate called after throwing an instance of 'ts::api::Exception'
  what():  [src/runtime/instruction.cpp:65]: Check failed: (stack.size() >= static_cast<size_t>(return_size)).
```

**Comment by tensorflower** [comment]
> 使用fastapi部署成http接口，jmeter2个线程请求正常，5个线程就报错，整个程序被杀死
> 
> ```
> [ERROR]: [src/runtime/instruction.cpp:65]: Check failed: (stack.size() >= static_cast<size_t>(return_size)).
> terminate called after throwing an instance of 'ts::api::Exception'
>   what():  [src/runtime/instruction.cpp:65]: Check failed: (stack.size() >= static_cast<size_t>(return_size)).
> ```

需要上线程锁，模块不能多线程
