### ISSUE TITLE
OSError: libSeetaFaceDetector600.so: cannot open shared object file

### ISSUE THREAD

**Issue by RUIXUEZHAOFENGNIAN** [tensorflower/seetaFace6Python#47]
linux环境下使用 python3.5 face_landmark_demo.py，用人遇到过类似问题吗？我确认了下，在seetaFace6Python-master/seetaface/lib/ubuntu/下是存在libSeetaFaceDetector600.so的

**Comment by tensorflower** [comment]
> linux环境下使用 python3.5 face_landmark_demo.py，用人遇到过类似问题吗？我确认了下，在seetaFace6Python-master/seetaface/lib/ubuntu/下是存在libSeetaFaceDetector600.so的
先确认是否有先添加动态库搜索路径，另外这个demo出这个问题吗 ，如果其他的demo都是这个问题的话，有可能是动态库搜索路径没有添加，另外就是查看查看机器以下几个指令集 是否都支持AVX | SSE | FMA

**Comment by RUIXUEZHAOFENGNIAN** [comment]
嗯，确实是{seetaFace6Python目录路径}没有替换成自己的。export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${seetaFace6Python目录路径}/seetaface/lib/ubuntu
