### ISSUE TITLE
使用过程中遇到的BUG

### ISSUE THREAD

**Issue by kdya2229** [tensorflower/seetaFace6Python#5]
1. centos 和 ubuntu下的文件名错误（/seetaface/api.py ）
`dll = CDLL(os.path.join(LIB_PATH, "libSeetaFaceAPI.so"))`
中 应该为 libSeetaFaceAPI.so 而不是 libFaceAPI.so， 文件名不对

2. 如果起始路径不是源目录下，会导致调用dll时候出现引用model问题（相对路径问题）：
建议在初始化的时候套一层装饰器，修改相对路径。
`def chcwd(origin_func):
    def wrapper(self, *args, **kwargs):
        cwd = os.getcwd()
        os.chdir(os.path.dirname(os.path.abspath(__file__)) + "/../")
        u = origin_func(self, *args, **kwargs)
        os.chdir(cwd)
        return u
    return wrapper

class SeetaFace(object):
    @chcwd
    def __init__(self, init_mask):
        self._init_mask = init_mask
        self._dll_func_def()
        self._init_engine()`

**Comment by tensorflower** [comment]
> 1. centos 和 ubuntu下的文件名错误（/seetaface/api.py ）
>    `dll = CDLL(os.path.join(LIB_PATH, "libSeetaFaceAPI.so"))`
>    中 应该为 libSeetaFaceAPI.so 而不是 libFaceAPI.so， 文件名不对
> 2. 如果起始路径不是源目录下，会导致调用dll时候出现引用model问题（相对路径问题）：
>    建议在初始化的时候套一层装饰器，修改相对路径。
>    `def chcwd(origin_func):
>    def wrapper(self, *args, **kwargs):
>    cwd = os.getcwd()
>    os.chdir(os.path.dirname(os.path.abspath(**file**)) + "/../")
>    u = origin_func(self, *args, **kwargs)
>    os.chdir(cwd)
>    return u
>    return wrapper
> 
> class SeetaFace(object):
> @chcwd
> def **init**(self, init_mask):
> self._init_mask = init_mask
> self._dll_func_def()
> self._init_engine()`

已修改，感谢反馈
