### ISSUE TITLE
centos7.6 and ubantu16.04 无法运行

### ISSUE THREAD

**Issue by yhbnet** [tensorflower/seetaFace6Python#52]
centos7.6错误 Unsupported platform:linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.10

ubantu16.04错误 Unsupported platform:linux-4.4.0-201-generic-x86_64-with-glibc2.10

求帮助！！！

**Comment by yhbnet** [comment]
解决了

**Comment by swimmant** [comment]
直接修改代码中 elif 检查平台名称的代码
