### ISSUE TITLE
如何只使用人脸识别模块？

### ISSUE THREAD

**Issue by Bilibotter** [tensorflower/seetaFace6Python#6]
作者你好，很感谢你做的项目。但是，我想使用自己的人脸检测与人脸对齐模块，而只使用SeetaFace的人脸识别模块，请问我该怎么做？我去看过源码了，但我太菜，Python与C++转化实在弄不懂...，尤其是类型c_float不知道是怎么来的..

**Comment by tensorflower** [comment]
> 作者你好，很感谢你做的项目。但是，我想使用自己的人脸检测与人脸对齐模块，而只使用SeetaFace的人脸识别模块，请问我该怎么做？我去看过源码了，但我太菜，Python与C++转化实在弄不懂...，尤其是类型c_float不知道是怎么来的..

这个就需要根据自己实际项目代码来改，我没看到你的实际代码，不知道

**Comment by Bilibotter** [comment]
感谢作者回复，我又看了一下代码，已经解决问题了，我需要的是seetaFace.ExtractCroppedFace()这个API。但是活体检测开摄像头后一直将我本人判定为假..，而且SCORE一直为0.0...
