### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by lwx19880330** [tensorflower/seetaFace6Python#7]
作者你好，关于gpu的setting怎么设置啊 会提供python api吗

**Comment by tensorflower** [comment]
> 作者你好，关于gpu的setting怎么设置啊 会提供python api吗

你已经问过好多次了，我回复过了，gpu设置不提供，目前开源的seetaface本身也没法用gpu，和你有没有这个设置没关系，设置了也是使用cpu

**Comment by lwx19880330** [comment]
谢谢你，不好意思 我才看到 ，谢谢啦
