### ISSUE TITLE
感谢作者的开源

### ISSUE THREAD

**Issue by yangbisheng2009** [tensorflower/seetaFace6Python#8]
我有两个问题需要请教大神：
1、这个工程的前提是不是还要把seetaface6那一套编译安装给弄好
2、作者有没有尝试过戴口罩的情况，能识别么？（我看seetaface6是说可以识别口罩）

感谢感谢！

**Comment by tensorflower** [comment]
> 我有两个问题需要请教大神：
> 1、这个工程的前提是不是还要把seetaface6那一套编译安装给弄好
> 2、作者有没有尝试过戴口罩的情况，能识别么？（我看seetaface6是说可以识别口罩）
> 
> 感谢感谢！

有python就行（python 安装了opencv库），口罩识别在人脸关键点检测demo里
