### ISSUE TITLE
win环境下报错

### ISSUE THREAD

**Issue by yangbisheng2009** [tensorflower/seetaFace6Python#9]
![微信截图_20200529123622](https://user-images.githubusercontent.com/17609763/83221720-232e4000-a1a9-11ea-92e8-8d3bb5acd6e3.png)
我没装vs2015，不知道是不是找个原因

**Comment by tensorflower** [comment]
> ![微信截图_20200529123622](https://user-images.githubusercontent.com/17609763/83221720-232e4000-a1a9-11ea-92e8-8d3bb5acd6e3.png)
> 我没装vs2015，不知道是不是找个原因

许哟啊64位的python，看看四不是自己下载的32位python
